spring:
  application:
    name: spring-testing-demo
  datasource:
    url: jdbc:h2:mem:testing_demo;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
